import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// Salat notifications are wall-clock alarms: they must fire at the minute.
///
/// SCHEDULE_EXACT_ALARM alone is NOT enough — Android 14+ does not auto-grant
/// it, so `canScheduleExactNotifications()` returns false and the scheduler
/// silently degrades to `inexactAllowWhileIdle`. Observed on an OxygenOS device
/// with the app battery-exempt: every pending salat alarm carried
/// `window=+1h0m0s0ms flags=0x8`, i.e. up to an hour late, batched, and posted
/// in Doze without the alert — the "no sound / doesn't fire" report.
///
/// USE_EXACT_ALARM (Android 13+) is granted at install for alarm-clock-style
/// apps and is what keeps the alarms exact. Both the manifest and the
/// re-apply tool (android/ can be regenerated by `flutter create`) must carry
/// it, and SCHEDULE_EXACT_ALARM must stay capped at API 32 — Play rejects an
/// app that declares both unbounded.
void main() {
  final manifest =
      File('android/app/src/main/AndroidManifest.xml').readAsStringSync();
  final tool = File('tool/apply_notification_config.py').readAsStringSync();

  for (final entry in {
    'AndroidManifest.xml': manifest,
    'tool/apply_notification_config.py': tool,
  }.entries) {
    group(entry.key, () {
      test('declares USE_EXACT_ALARM', () {
        expect(
          entry.value,
          contains('android.permission.USE_EXACT_ALARM'),
        );
      });

      test('caps SCHEDULE_EXACT_ALARM at API 32', () {
        final schedule = RegExp(
          r'<uses-permission[^>]*android\.permission\.SCHEDULE_EXACT_ALARM'
          r'[^>]*/>',
          dotAll: true,
        ).firstMatch(entry.value);
        expect(
          schedule,
          isNotNull,
          reason: 'SCHEDULE_EXACT_ALARM declaration missing',
        );
        expect(schedule![0], contains('android:maxSdkVersion="32"'));
      });
    });
  }
}
