#!/usr/bin/env python3
"""Re-apply the prayer-times location permissions to the native projects.

`android/` and `ios/` are gitignored (regenerated by `flutter create`), so the
ACCESS_*_LOCATION manifest entries and the NSLocationWhenInUseUsageDescription
plist key don't survive a regen. Run this (via `make location-perms`) after any
`flutter create` to put them back. Idempotent — safe to run repeatedly.

Mirrors tool/patch_arabic_font.py: a small, self-contained, re-runnable fixup.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ANDROID_MANIFEST = ROOT / "android/app/src/main/AndroidManifest.xml"
IOS_PLIST = ROOT / "ios/Runner/Info.plist"

ANDROID_PERMS = """    <!-- Prayer times: device location to compute the daily schedule on-device.
         Coarse is enough (city-level); fine sharpens accuracy near borders.
         Re-apply after a `flutter create` regen — see `make location-perms`. -->
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
"""

IOS_KEY = """	<!-- Prayer times: location to compute the daily schedule on-device.
	     Re-apply after a `flutter create` regen — see `make location-perms`. -->
	<key>NSLocationWhenInUseUsageDescription</key>
	<string>Al Quran uses your location to calculate accurate prayer times for where you are.</string>
"""


def patch_android() -> str:
    if not ANDROID_MANIFEST.exists():
        return f"skip  android — {ANDROID_MANIFEST} not found (run `flutter create`)"
    text = ANDROID_MANIFEST.read_text()
    if "ACCESS_FINE_LOCATION" in text:
        return "ok    android — location permissions already present"
    anchor = "    <application"
    if anchor not in text:
        return "ERROR android — could not find <application> anchor"
    text = text.replace(anchor, ANDROID_PERMS + anchor, 1)
    ANDROID_MANIFEST.write_text(text)
    return "added android — ACCESS_COARSE/FINE_LOCATION"


def patch_ios() -> str:
    if not IOS_PLIST.exists():
        return f"skip  ios — {IOS_PLIST} not found (run `flutter create`)"
    text = IOS_PLIST.read_text()
    if "NSLocationWhenInUseUsageDescription" in text:
        return "ok    ios — location usage description already present"
    anchor = "<dict>\n"
    idx = text.find(anchor)
    if idx == -1:
        return "ERROR ios — could not find <dict> anchor"
    insert_at = idx + len(anchor)
    text = text[:insert_at] + IOS_KEY + text[insert_at:]
    IOS_PLIST.write_text(text)
    return "added ios — NSLocationWhenInUseUsageDescription"


def main() -> int:
    results = [patch_android(), patch_ios()]
    for line in results:
        print(line)
    return 1 if any(r.startswith("ERROR") for r in results) else 0


if __name__ == "__main__":
    sys.exit(main())
