#!/usr/bin/env python3
"""Re-apply the Sunnah-reminders notification config to the native projects.

`android/` and `ios/` are gitignored (regenerated by `flutter create`), so the
notification permission + the flutter_local_notifications boot/scheduled
receivers don't survive a regen. Run this (via `make notif-perms`) after any
`flutter create` to put them back. Idempotent — safe to run repeatedly.

Android only: POST_NOTIFICATIONS + RECEIVE_BOOT_COMPLETED, plus the FLN
receivers that re-arm pending notifications after a reboot / app update. We use
INEXACT scheduling, so SCHEDULE_EXACT_ALARM is deliberately NOT added. iOS needs
no change for v1 — permission is requested from Dart and the plugin auto-registers
(notifications deliver in the background; foreground-presentation delegate is a
follow-up). Mirrors tool/apply_location_perms.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ANDROID_MANIFEST = ROOT / "android/app/src/main/AndroidManifest.xml"

ANDROID_PERMS = """    <!-- Sunnah reminders (local notifications). No SCHEDULE_EXACT_ALARM — we
         use inexact scheduling. Re-apply after a `flutter create` regen — see
         `make notif-perms`. -->
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
"""

ANDROID_RECEIVERS = """        <!-- Sunnah reminders (flutter_local_notifications): re-arm pending
             notifications after a reboot / app update. Re-apply after a
             `flutter create` regen — see `make notif-perms`. -->
        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver"
            android:exported="false" />
"""


def patch_android() -> list[str]:
    if not ANDROID_MANIFEST.exists():
        return [f"skip  android — {ANDROID_MANIFEST} not found (run `flutter create`)"]
    text = ANDROID_MANIFEST.read_text()
    out: list[str] = []

    if "POST_NOTIFICATIONS" in text:
        out.append("ok    android — notification permissions already present")
    else:
        anchor = "    <application"
        if anchor not in text:
            return ["ERROR android — could not find <application> anchor"]
        text = text.replace(anchor, ANDROID_PERMS + anchor, 1)
        out.append("added android — POST_NOTIFICATIONS + RECEIVE_BOOT_COMPLETED")

    if "ScheduledNotificationBootReceiver" in text:
        out.append("ok    android — FLN receivers already present")
    else:
        anchor = "    </application>"
        if anchor not in text:
            return out + ["ERROR android — could not find </application> anchor"]
        text = text.replace(anchor, ANDROID_RECEIVERS + anchor, 1)
        out.append("added android — FLN boot/scheduled receivers")

    ANDROID_MANIFEST.write_text(text)
    return out


def main() -> int:
    results = patch_android()
    results.append("note  ios — no change needed for v1 (Dart permission + auto-register)")
    for line in results:
        print(line)
    return 1 if any(r.startswith("ERROR") for r in results) else 0


if __name__ == "__main__":
    sys.exit(main())
