#!/usr/bin/env python3
"""Re-apply the audio-recitation network config to the native projects.

`android/` and `ios/` are gitignored (regenerated by `flutter create`), so the
permissions / network exceptions below don't survive a regen. Run this (via
`make audio-perms`) after any `flutter create` to put them back. Idempotent — safe
to run repeatedly.

What it adds (the MINIMAL set for foreground HTTPS streaming + on-device caching):
  * Android — INTERNET permission (Flutter's debug/profile manifests add it
    automatically, but the RELEASE manifest does NOT), AND a network-security-config
    that permits cleartext ONLY to localhost. just_audio's LockCachingAudioSource
    (stream + cache) plays through a localhost HTTP proxy, and Android blocks
    cleartext HTTP by default (targetSdk >= 28), so playback fails without it. The
    CDN itself is HTTPS, so general cleartext stays blocked. No RECORD_AUDIO / no
    FOREGROUND_SERVICE (we don't record; background playback is deferred).
  * iOS — NSAppTransportSecurity → NSAllowsLocalNetworking, the exact same
    localhost-proxy exception for iOS ATS. NOT NSAllowsArbitraryLoads (CDN is HTTPS)
    and NOT UIBackgroundModes (background deferred).

Mirrors tool/apply_location_perms.py: a small, self-contained, re-runnable fixup.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ANDROID_MANIFEST = ROOT / "android/app/src/main/AndroidManifest.xml"
ANDROID_NSC = ROOT / "android/app/src/main/res/xml/network_security_config.xml"
IOS_PLIST = ROOT / "ios/Runner/Info.plist"

ANDROID_PERMS = """    <!-- Audio recitation: stream verse audio from the CDN (and cache it). The
         release manifest doesn't get INTERNET for free — see `make audio-perms`. -->
    <uses-permission android:name="android.permission.INTERNET" />
"""

# Inserted into the <application> tag, right after the (always-present) name attr.
APP_NAME_ANCHOR = '        android:name="${applicationName}"\n'
NSC_ATTR = '        android:networkSecurityConfig="@xml/network_security_config"\n'

NSC_CONTENT = """<?xml version="1.0" encoding="utf-8"?>
<!-- Audio recitation: just_audio's LockCachingAudioSource (stream + cache) plays
     through a localhost HTTP proxy, and Android blocks cleartext HTTP by default
     (targetSdk >= 28). Permit cleartext ONLY to the loopback addresses; the CDN
     itself is HTTPS, so general cleartext stays blocked. Mirrors the iOS
     NSAllowsLocalNetworking exception. Re-applied by `make audio-perms`. -->
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="false">127.0.0.1</domain>
        <domain includeSubdomains="false">localhost</domain>
    </domain-config>
</network-security-config>
"""

IOS_KEY = """	<!-- Audio recitation: just_audio's stream+cache source proxies through
	     localhost (plain HTTP), which iOS ATS blocks by default. Allow only local
	     networking — the CDN itself is HTTPS. Re-apply after a `flutter create`
	     regen — see `make audio-perms`. -->
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsLocalNetworking</key>
		<true/>
	</dict>
"""


def patch_android_manifest() -> str:
    if not ANDROID_MANIFEST.exists():
        return f"skip  android manifest — {ANDROID_MANIFEST} not found (run `flutter create`)"
    text = ANDROID_MANIFEST.read_text()
    added = []
    if "android.permission.INTERNET" not in text:
        anchor = "    <application"
        if anchor not in text:
            return "ERROR android manifest — could not find <application> anchor"
        text = text.replace(anchor, ANDROID_PERMS + anchor, 1)
        added.append("INTERNET")
    if "networkSecurityConfig" not in text:
        if APP_NAME_ANCHOR not in text:
            return "ERROR android manifest — could not find android:name anchor"
        text = text.replace(APP_NAME_ANCHOR, APP_NAME_ANCHOR + NSC_ATTR, 1)
        added.append("networkSecurityConfig")
    if not added:
        return "ok    android manifest — INTERNET + networkSecurityConfig already present"
    ANDROID_MANIFEST.write_text(text)
    return f"added android manifest — {', '.join(added)}"


def write_android_nsc() -> str:
    if not ANDROID_MANIFEST.exists():
        return "skip  android nsc — no android/ project (run `flutter create`)"
    if ANDROID_NSC.exists() and "127.0.0.1" in ANDROID_NSC.read_text():
        return "ok    android nsc — network_security_config.xml already present"
    ANDROID_NSC.parent.mkdir(parents=True, exist_ok=True)
    ANDROID_NSC.write_text(NSC_CONTENT)
    return "added android nsc — res/xml/network_security_config.xml"


def patch_ios() -> str:
    if not IOS_PLIST.exists():
        return f"skip  ios — {IOS_PLIST} not found (run `flutter create`)"
    text = IOS_PLIST.read_text()
    if "NSAppTransportSecurity" in text:
        return "ok    ios — App Transport Security exception already present"
    anchor = "<dict>\n"
    idx = text.find(anchor)
    if idx == -1:
        return "ERROR ios — could not find <dict> anchor"
    insert_at = idx + len(anchor)
    text = text[:insert_at] + IOS_KEY + text[insert_at:]
    IOS_PLIST.write_text(text)
    return "added ios — NSAppTransportSecurity/NSAllowsLocalNetworking"


def main() -> int:
    results = [patch_android_manifest(), write_android_nsc(), patch_ios()]
    for line in results:
        print(line)
    return 1 if any(r.startswith("ERROR") for r in results) else 0


if __name__ == "__main__":
    sys.exit(main())
