#!/usr/bin/env python3
"""Re-apply the Sunnah-reminders notification config to the native projects.

`android/` and `ios/` are gitignored (regenerated by `flutter create`), so the
notification permission + the flutter_local_notifications boot/scheduled
receivers don't survive a regen. Run this (via `make notif-perms`) after any
`flutter create` to put them back. Idempotent — safe to run repeatedly.

Android: POST_NOTIFICATIONS + RECEIVE_BOOT_COMPLETED + SCHEDULE_EXACT_ALARM +
REQUEST_IGNORE_BATTERY_OPTIMIZATIONS, plus the FLN receivers that re-arm pending
notifications after a reboot / app update. Reminders fire at an EXACT minute
(SCHEDULE_EXACT_ALARM) and the app can prompt the user to exempt itself from
battery optimization so aggressive OEMs don't freeze the alarm.

iOS: set the UNUserNotificationCenter delegate in AppDelegate.swift so a
notification fired while the app is FOREGROUNDED is presented (the plugin's
`willPresentNotification` needs the delegate; FlutterAppDelegate forwards to it).
Without it, the "send a test reminder" button shows nothing on-screen while the
app is open (background-delivered reminders are unaffected). Mirrors
tool/apply_location_perms.py.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ANDROID_MANIFEST = ROOT / "android/app/src/main/AndroidManifest.xml"
IOS_APPDELEGATE = ROOT / "ios/Runner/AppDelegate.swift"

# Set in application(_:didFinishLaunchingWithOptions:), before the super call.
IOS_DELEGATE = """    // Sunnah reminders: present notifications while the app is foregrounded
    // (flutter_local_notifications' willPresentNotification needs the delegate).
    // Re-apply after a `flutter create` regen — see `make notif-perms`.
    if #available(iOS 10.0, *) {
      UNUserNotificationCenter.current().delegate = self
    }
"""

ANDROID_PERMS = """    <!-- Sunnah reminders (local notifications) with EXACT-time delivery.
         SCHEDULE_EXACT_ALARM fires the reminder at the set minute even in Doze
         (user-granted on Android 14+); REQUEST_IGNORE_BATTERY_OPTIMIZATIONS lets
         the app prompt to exempt itself so aggressive OEMs don't freeze the alarm.
         Re-apply after a `flutter create` regen — see `make notif-perms`. -->
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />
"""

ANDROID_RECEIVERS = """        <!-- Sunnah reminders (flutter_local_notifications): re-arm pending
             notifications after a reboot / app update. Re-apply after a
             `flutter create` regen — see `make notif-perms`. -->
        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationBootReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED" />
                <action android:name="android.intent.action.MY_PACKAGE_REPLACED" />
            </intent-filter>
        </receiver>
        <receiver
            android:name="com.dexterous.flutterlocalnotifications.ScheduledNotificationReceiver"
            android:exported="false" />
"""


def patch_android() -> list[str]:
    if not ANDROID_MANIFEST.exists():
        return [f"skip  android — {ANDROID_MANIFEST} not found (run `flutter create`)"]
    text = ANDROID_MANIFEST.read_text()
    out: list[str] = []

    if "POST_NOTIFICATIONS" in text:
        out.append("ok    android — notification permissions already present")
    else:
        anchor = "    <application"
        if anchor not in text:
            return ["ERROR android — could not find <application> anchor"]
        text = text.replace(anchor, ANDROID_PERMS + anchor, 1)
        out.append("added android — POST_NOTIFICATIONS + RECEIVE_BOOT_COMPLETED")

    if "ScheduledNotificationBootReceiver" in text:
        out.append("ok    android — FLN receivers already present")
    else:
        anchor = "    </application>"
        if anchor not in text:
            return out + ["ERROR android — could not find </application> anchor"]
        text = text.replace(anchor, ANDROID_RECEIVERS + anchor, 1)
        out.append("added android — FLN boot/scheduled receivers")

    ANDROID_MANIFEST.write_text(text)
    return out


def patch_ios() -> str:
    if not IOS_APPDELEGATE.exists():
        return f"skip  ios — {IOS_APPDELEGATE} not found (run `flutter create`)"
    text = IOS_APPDELEGATE.read_text()
    if "UNUserNotificationCenter.current().delegate" in text:
        return "ok    ios — notification delegate already set"

    # `UNUserNotificationCenter` lives in the UserNotifications framework.
    if "import UserNotifications" not in text:
        text = text.replace("import UIKit", "import UIKit\nimport UserNotifications", 1)

    anchor = (
        "    return super.application(application, "
        "didFinishLaunchingWithOptions: launchOptions)"
    )
    if anchor not in text:
        return "ERROR ios — could not find didFinishLaunchingWithOptions return anchor"
    text = text.replace(anchor, IOS_DELEGATE + anchor, 1)
    IOS_APPDELEGATE.write_text(text)
    return "added ios — UNUserNotificationCenter delegate (foreground presentation)"


def main() -> int:
    results = [*patch_android(), patch_ios()]
    for line in results:
        print(line)
    return 1 if any(r.startswith("ERROR") for r in results) else 0


if __name__ == "__main__":
    sys.exit(main())
