@TestOn('vm')
library;

import 'dart:io';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';

/// Regression guard for the release "blank icons" bug (LEARNINGS.md §4).
///
/// In-app icons are Material Symbols Rounded, rendered from a bundled subset
/// (assets/fonts/MaterialSymbolsRounded.ttf) generated by
/// tools/icon/subset_symbols.py — NOT the package font, because Flutter's
/// release icon tree-shaking corrupts that 4-axis variable font and blanks every
/// filled / non-default-size icon. These tests fail fast if:
///   1. an AppIcons glyph isn't in the bundled font (someone added an icon but
///      forgot to regenerate the subset), or
///   2. the bundled font lost its variable axes (flattened / corrupted), or
///   3. a release build path dropped `--no-tree-shake-icons` (which would let
///      Flutter re-corrupt the font in release).
void main() {
  final fontFile = File('assets/fonts/MaterialSymbolsRounded.ttf');

  test('every AppIcons codepoint is present in the bundled icon font', () {
    final used = _appIconsCodepoints();
    expect(
      used,
      isNotEmpty,
      reason: 'No IconData codepoints found in app_icons.dart',
    );

    final cmap = _Ttf(fontFile.readAsBytesSync()).codepoints();
    final missing = used.where((c) => !cmap.contains(c)).toList()..sort();

    expect(
      missing,
      isEmpty,
      reason: 'These AppIcons glyphs are missing from '
          'assets/fonts/MaterialSymbolsRounded.ttf: '
          '${missing.map((c) => '0x${c.toRadixString(16)}').join(', ')}. '
          'Run `python3 tools/icon/subset_symbols.py` after adding/removing an icon.',
    );
  });

  test('bundled icon font keeps its variable axes (fvar)', () {
    final font = _Ttf(fontFile.readAsBytesSync());
    expect(
      font.hasTable('fvar'),
      isTrue,
      reason:
          'The icon font lost its variable axes — filled / non-default-size '
          'icons will render blank. Regenerate with tools/icon/subset_symbols.py.',
    );
  });

  test('bundled icon font is the small subset, not the full package font', () {
    // The full Material Symbols Rounded font is ~14 MB; our subset is ~0.1 MB.
    expect(
      fontFile.lengthSync(),
      lessThan(2 * 1024 * 1024),
      reason:
          'Icon font is unexpectedly large — is the full package font bundled '
          'instead of the subset?',
    );
  });

  test('release builds keep --no-tree-shake-icons', () {
    // Without this flag Flutter re-corrupts the variable icon font in release.
    const flag = '--no-tree-shake-icons';
    for (final path in const [
      'Makefile',
      '.github/workflows/flutter-release.yml',
    ]) {
      expect(
        File(path).readAsStringSync().contains(flag),
        isTrue,
        reason: '$path must build release with $flag (see LEARNINGS.md §4).',
      );
    }
  });
}

/// Codepoints referenced by `IconData(0x..)` in the icon registry.
Set<int> _appIconsCodepoints() {
  final src = File('lib/core/theme/app_icons.dart').readAsStringSync();
  return RegExp(r'IconData\(\s*0x([0-9a-fA-F]+)')
      .allMatches(src)
      .map((m) => int.parse(m.group(1)!, radix: 16))
      .toSet();
}

/// Minimal TrueType reader: table directory + the Unicode `cmap` (formats 4/12).
class _Ttf {
  _Ttf(Uint8List bytes)
      : _d = ByteData.sublistView(bytes),
        _bytes = bytes {
    final numTables = _d.getUint16(4);
    for (var i = 0, p = 12; i < numTables; i++, p += 16) {
      final tag = String.fromCharCodes(_bytes.sublist(p, p + 4));
      _tableOffset[tag] = _d.getUint32(p + 8);
    }
  }

  final ByteData _d;
  final Uint8List _bytes;
  final Map<String, int> _tableOffset = {};

  bool hasTable(String tag) => _tableOffset.containsKey(tag);

  /// All Unicode codepoints mapped to a non-zero glyph.
  Set<int> codepoints() {
    final cmapOff = _tableOffset['cmap']!;
    final numSub = _d.getUint16(cmapOff + 2);
    int? subOff;
    var bestScore = -1;
    for (var i = 0; i < numSub; i++) {
      final p = cmapOff + 4 + i * 8;
      final plat = _d.getUint16(p);
      final enc = _d.getUint16(p + 2);
      final score = (plat == 3 && enc == 10)
          ? 4 // Windows full (UCS-4)
          : (plat == 3 && enc == 1)
              ? 3 // Windows BMP
              : (plat == 0)
                  ? 2 // Unicode
                  : 0;
      if (score > bestScore) {
        bestScore = score;
        subOff = cmapOff + _d.getUint32(p + 4);
      }
    }

    final result = <int>{};
    final off = subOff!;
    final format = _d.getUint16(off);
    if (format == 4) {
      final segX2 = _d.getUint16(off + 6);
      final endOff = off + 14;
      final startOff = endOff + segX2 + 2; // + reservedPad
      final deltaOff = startOff + segX2;
      final rangeOff = deltaOff + segX2;
      for (var s = 0; s < segX2 ~/ 2; s++) {
        final end = _d.getUint16(endOff + s * 2);
        final start = _d.getUint16(startOff + s * 2);
        if (start == 0xffff) continue;
        final delta = _d.getUint16(deltaOff + s * 2);
        final rangeOffset = _d.getUint16(rangeOff + s * 2);
        for (var c = start; c <= end; c++) {
          int gid;
          if (rangeOffset == 0) {
            gid = (c + delta) & 0xffff;
          } else {
            gid =
                _d.getUint16(rangeOff + s * 2 + rangeOffset + (c - start) * 2);
            if (gid != 0) gid = (gid + delta) & 0xffff;
          }
          if (gid != 0) result.add(c);
        }
      }
    } else if (format == 12) {
      final nGroups = _d.getUint32(off + 12);
      for (var g = 0, p = off + 16; g < nGroups; g++, p += 12) {
        for (var c = _d.getUint32(p); c <= _d.getUint32(p + 4); c++) {
          result.add(c);
        }
      }
    }
    return result;
  }
}
